version: "3.4"

services:
  autotrader:
    image: autotrader
    build:
      context: .
      dockerfile: ./Dockerfile

  ibkr:
    image: ghcr.io/extrange/ibkr # latest, stable, 10.21, 10.21.1p etc
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:8888:8888" # API access
    ulimits:
      nofile: 10000 # See FAQ
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      TWOFA_TIMEOUT_ACTION: restart
      GATEWAY_OR_TWS: tws
      #
      # Variables prefixed with IBC_ override IBCAlpha`s config.ini:
      IBC_TradingMode: paper
      IBC_ReadOnlyApi: no
      # ...
      # See below for more details
  # ibeam:
  #   image: voyz/ibeam
  #   container_name: ibeam
  #   env_file:
  #     - env.list
  #   ports:
  #     - 5000:5000
  #     - 5001:5001
  #   network_mode: bridge # Required due to clientportal.gw IP whitelist
  #   restart: "no" # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
  # ib-gateway:
  #   image: waytrade/ib-gateway:981.3j
  #   restart: always
  #   environment:
  #     TWS_USERID: ${TWS_USERID}
  #     TWS_PASSWORD: ${TWS_PASSWORD}
  #     TRADING_MODE: ${TRADING_MODE:-paper}
  #     VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
  #   ports:
  #     - "127.0.0.1:4001:4001"
  #     - "127.0.0.1:4002:4002"
  #     - "127.0.0.1:5900:5900"
